apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-app
  labels:
    app: form-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-app
  template:
    metadata:
      labels:
        app: form-app
    spec:
      containers:
      - name: form-app
        image: asia-northeast1-docker.pkg.dev/sreake-intern/repo-summer-2024-k-takahashi/app:921b106a7cf23cbf7e073deb7be7a07d05f5966c
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: form-service
  labels:
    app: form-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: form-app