apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-app
  labels:
    app: form-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-app
  template:
    metadata:
      labels:
        app: form-app
    spec:
      containers:
      - name: form-app
        image: asia-northeast1-docker.pkg.dev/sreake-intern/repo-summer-2024-k-takahashi/app@sha256:950b181ebfbd7c089e562e18ea6aba5eb998b9320074f4fdd53cfdb8d67b5f85
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: form-service
  labels:
    app: form-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: form-app