apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-app
  labels:
    app: form-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: form-app
  template:
    metadata:
      labels:
        app: form-app
    spec:
      containers:
      - name: form-app
        image: asia-northeast1-docker.pkg.dev/sreake-intern/repo-summer-2024-k-takahashi/app@sha256:dceb6c8b4288cbb5db2ef529c9f883181b9887ecc7e5765096ff821f7990f6e2
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: form-service
  labels:
    app: form-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: form-app